### ISSUE TITLE
User With No Signature Error When Preview or Email

### ISSUE THREAD

**Issue by ghost** [berryte/cs467_ERP2#26]
Steps:
1. Create a new user
2. Log in with newly created user
3. Create an award
4. Click on Preview or Email

Result
App crashes

```
/usr/src/app/node_modules/mysql/lib/protocol/Parser.js:437
node_1     |       throw err; // Rethrow non-MySQL errors
node_1     |       ^
node_1     | 
node_1     | TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object
node_1     |     at Function.from (buffer.js:207:11)
node_1     |     at Query.db.pool.query (/usr/src/app/api/awards/router.js:29:40)
node_1     |     at Query.<anonymous> (/usr/src/app/node_modules/mysql/lib/Connection.js:525:10)
node_1     |     at Query._callback (/usr/src/app/node_modules/mysql/lib/Connection.js:491:16)
node_1     |     at Query.Sequence.end (/usr/src/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
node_1     |     at Query._handleFinalResultPacket (/usr/src/app/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
node_1     |     at Query.EofPacket (/usr/src/app/node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
node_1     |     at Protocol._parsePacket (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
node_1     |     at Parser._parsePacket (/usr/src/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
node_1     |     at Parser.write (/usr/src/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
node_1     | npm ERR! code ELIFECYCLE
node_1     | npm ERR! errno 1
node_1     | npm ERR! emport@1.0.0 start: `node app.js`
node_1     | npm ERR! Exit status 1
node_1     | npm ERR! 
node_1     | npm ERR! Failed at the emport@1.0.0 start script.
node_1     | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
node_1     | 
node_1     | npm ERR! A complete log of this run can be found in:
node_1     | npm ERR!     /root/.npm/_logs/2019-06-03T01_48_35_668Z-debug.log
```

**Comment by ghost** [comment]
fixed in #35
